version: '3.9'
services:
  word_embd_server:
    build: ./word_embedding
    ports:
      - '9600:9600'
        #command: ["--data_dir", "data", "--word_embed_file", "wiki-news-300d-1M.txt"]
    volumes:
      - ./data:/app/data

  kgqan_server:
    build: ./src/kgqan
    ports:
      - '8899:8899'
    depends_on:
      - word_embd_server
        #command: ["--data_dir", "cache", "--model_name", "output_pred21_8_30"]
    # volumes:
    # - ./data/cache:/app/cache

